### ISSUE TITLE
Image size is too small and Not able to see while zoom in.

### ISSUE THREAD

**Issue by peer4infotech** [IvanReznikov/DataVerse#1]
Image size is too small and Not able to see while zoom in.

**Comment by IvanReznikov** [comment]
@peer4infotech , have you checked the links that are attached in the .md files?
As an example: https://github.com/IvanReznikov/DataVerse/blob/main/Onepagers/onepager_python_basics.md

**Comment by peer4infotech** [comment]
Yeah checked that.  Thank you
